source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SDPathKalmanFilter_Example', :exclusive => true do
  pod "SDPathKalmanFilter", :path => "../"
end

target 'SDPathKalmanFilter_Tests', :exclusive => true do
  pod "SDPathKalmanFilter", :path => "../"

  
end
